import sys
import os

from kivy.core.window import Window
from kivy.utils import platform
from kivy.app import App
import pygame


APP_VERSION = 0.78

MAINMENU_BUTTON_TEXT_SIZE = 22
BUTTON_TEXT_SIZE = 18

APP = App.get_running_app
KEY_ESCAPE = pygame.K_ESCAPE

USE_KIVY_SETTINGS = 0

DEFAULT_IMAGE_SIZE = (128, 64)

WIN_WIDTH = Window.width
WIN_HEIGHT = Window.height
BTN_WIDTH = Window.width * 0.6
BTN_HEIGHT = Window.height * 0.6

WIN_ASPECT = float(WIN_WIDTH) / WIN_HEIGHT
WIN_REVERSE_ASPECT = float(WIN_HEIGHT) / WIN_WIDTH

PALETTE_BTN_COUNT = 10

BTN_SHOW_TOOLBAR_SIZE_HINT = (0.05, 0.1)

PALETTE_BTN_SIZE_HINT = (1.0 / 2, 1.0 / (PALETTE_BTN_COUNT + 2))
PALETTE_LAYOUT_CLMN_SIZE_HINT = (0.05, 1)
PALETTE_LAYOUT_SIZE_HINT = (
    PALETTE_BTN_SIZE_HINT[1] * 2 * WIN_REVERSE_ASPECT, PALETTE_BTN_SIZE_HINT[1] * PALETTE_BTN_COUNT)
PALETTE_LAYOUT_POS_HINT = (1.0 - PALETTE_LAYOUT_SIZE_HINT[0], PALETTE_BTN_SIZE_HINT[1])
PALETTE_BTN_SHOW_SIZE_HINT = (1.0 / (PALETTE_BTN_COUNT + 2) * WIN_REVERSE_ASPECT, 1.0 / (PALETTE_BTN_COUNT + 2))

TOOLBAR_BTN_COUNT = 6

TOOLBAR_LAYOUT_SIZE_HINT = (
    PALETTE_LAYOUT_SIZE_HINT[1] / TOOLBAR_BTN_COUNT * 2 * WIN_REVERSE_ASPECT, PALETTE_LAYOUT_SIZE_HINT[1])
TOOLBAR_LAYOUT_POS_HINT = (0, PALETTE_BTN_SIZE_HINT[1])
TOOLBAR_LAYOUT_CLMN_SIZE_HINT = (0.5, 1)

MENU_ENTRY_HEIGHT_HINT = 0.12

WIN_WIDTH = Window.width
WIN_HEIGHT = Window.height
BTN_WIDTH = Window.width * 0.6
BTN_HEIGHT = Window.height * 0.6

LAYER_RIBBON_WIDTH_HINT = 0.20
LAYER_RIBBON_SIZE_HINT = (0.20, PALETTE_LAYOUT_SIZE_HINT[1])

LAYER_RIBBON_POS_HINT_2 = (1 - (PALETTE_LAYOUT_SIZE_HINT[0] + LAYER_RIBBON_SIZE_HINT[0]), PALETTE_BTN_SIZE_HINT[1])
LAYER_RIBBON_POS_HINT_1 = (1 - LAYER_RIBBON_SIZE_HINT[0], PALETTE_BTN_SIZE_HINT[1])

LAYER_RIBBON_BUTTON_HEIGHT_HINT = PALETTE_BTN_SIZE_HINT[1]
LAYERBOX_PADDING = [3, 3, 3, 3]

DRAWAREA_SIZE = (Window.width, Window.height)

if platform() == 'android':
    DEF_PATH = unicode(os.path.splitdrive(sys.argv[0])[0] + '/')
else:
    DEF_PATH = unicode(os.path.splitdrive(sys.argv[0])[0] + '/')

TOOL_PICKER = 2
TOOL_FILL = 3
TOOL_SELECT = 4
TOOL_MOVE = 5
TOOL_RECT = 6
TOOL_LINE = 7
TOOL_ELLIPSE = 8
TOOL_POLYGON = 9
TOOL_POLYLINE = 10
TOOL_PENCIL1 = 11
TOOL_PENCIL2 = 12
TOOL_PENCIL3 = 13
TOOL_ERASE1 = 14
TOOL_ERASE2 = 15
TOOL_ERASE3 = 16

STATE_ROOT = 0
STATE_MENU = 1
STATE_SETTINGS = 2
STATE_DIALOG_EXIT = 3
STATE_DIALOG_COLOR = 4
STATE_DIALOG_NEW = 5
STATE_DIALOG_OPEN = 6
STATE_DIALOG_SAVE = 7


def data_path(path):
    ps = os.getcwd() + '/data/' + path
    result = os.path.abspath(ps)
    return result
